const ERR_NOT_FOUND = 404;
const ERR_BAD_REQUEST = 400;
const ERR_SERVER_ERROR = 500;
const ERR_CONFLICT_ERROR = 409;

module.exports = {
  ERR_NOT_FOUND,
  ERR_BAD_REQUEST,
  ERR_SERVER_ERROR,
  ERR_CONFLICT_ERROR,
};
